/**
 * The GitHub Actions side of acceptance tests and github labs. The learner adds
 * one workflow file, generated per connection, to their repo. On every push it
 * installs their project, fetches our tests from /api/ci/suite/<token>, runs them
 * with pytest exactly as `npm run content:acceptance` does locally, and posts the
 * results to /api/ci/report/<token>. The app then confirms the run with GitHub's
 * API before it counts (lib/ci/github.ts), so the posted results alone prove nothing.
 */

export const WORKFLOW_PATH = ".github/workflows/pylearn.yml";

/** How pytest runs the suite, here and in scripts/content/run_acceptance.py */
export const PYTEST_ARGS = [
  ".pylearn",
  "-c",
  ".pylearn/pytest.ini",
  "--rootdir",
  ".",
  // The learner's conftest.py and pytest settings can't change how our tests run
  "--noconftest",
  "-p",
  "no:cacheprovider",
  "-q",
  "--junitxml",
  ".pylearn/report.xml",
];

export const PYTEST_INI = `[pytest]
# The project's root is the working directory and is importable
pythonpath = .
testpaths = .pylearn
python_files = test_*.py
addopts =
`;

/** Posts the junit results back to pylearn (runs in the workflow, stdlib only) */
export const REPORT_PY = `"""Send this run's test results to pylearn. Generated by pylearn; runs in GitHub Actions."""
import json
import os
import urllib.request
import xml.etree.ElementTree as ET

tests = []
try:
    root = ET.parse(".pylearn/report.xml").getroot()
    for case in root.iter("testcase"):
        outcome, message = "passed", ""
        for tag in ("failure", "error"):
            node = case.find(tag)
            if node is not None:
                outcome = "failed"
                message = (node.get("message") or node.text or "").strip()[:500]
        if case.find("skipped") is not None:
            outcome = "skipped"
        name = case.get("name", "")
        tests.append({"name": name, "file": case.get("classname", ""), "outcome": outcome, "message": message})
except (OSError, ET.ParseError) as exc:
    tests = []
    print(f"No test report ({exc}); the tests probably didn't start. Check the install step.")

body = {
    "repository": os.environ.get("GITHUB_REPOSITORY", ""),
    "runId": os.environ.get("GITHUB_RUN_ID", ""),
    "sha": os.environ.get("GITHUB_SHA", ""),
    "runUrl": f"{os.environ.get('GITHUB_SERVER_URL', 'https://github.com')}/{os.environ.get('GITHUB_REPOSITORY', '')}/actions/runs/{os.environ.get('GITHUB_RUN_ID', '')}",
    "tests": tests,
}
request = urllib.request.Request(
    f"{os.environ['PYLEARN_URL']}/api/ci/report/{os.environ['PYLEARN_TOKEN']}",
    data=json.dumps(body).encode(),
    headers={"Content-Type": "application/json", "User-Agent": "pylearn-ci"},
    method="POST",
)
try:
    with urllib.request.urlopen(request, timeout=20) as response:
        print(json.loads(response.read() or b"{}").get("message", "Reported to pylearn."))
except Exception as exc:  # noqa: BLE001 - reporting must never hide the test result
    print(f"Couldn't reach pylearn ({exc}). Use Check now on the pylearn page.")
`;

/**
 * The files the workflow writes into .pylearn/ besides the tests themselves. pytest puts
 * .pylearn first on sys.path, so the reporter's name mustn't clash with a learner's module
 * (a capstone that asks for report.py would import ours instead).
 */
export const REPORTER = "_pylearn_report.py";

export function runnerFiles(): Record<string, string> {
  return { "pytest.ini": PYTEST_INI, [REPORTER]: REPORT_PY };
}

/**
 * The workflow for one connection. It's compared byte for byte (line endings and
 * trailing space aside) with the file GitHub ran, so it must stay deterministic.
 */
export function workflowYaml(opts: { origin: string; token: string; title: string }): string {
  const title = opts.title.replace(/[^\w .,'()&-]/g, "");
  return `# pylearn: runs the tests for "${title}" on every push and reports the result.
# Don't edit this file. pylearn checks it's unchanged before it counts a run.
name: pylearn
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  pylearn:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYLEARN_URL: "${opts.origin}"
      PYLEARN_TOKEN: "${opts.token}"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install your project
        run: |
          uv venv --python 3.13 .venv
          . .venv/bin/activate
          if [ -f pyproject.toml ]; then uv pip install -e . || uv pip install -r pyproject.toml; fi
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
      - name: Fetch the pylearn tests
        run: |
          . .venv/bin/activate
          mkdir -p .pylearn
          curl -fsS "$PYLEARN_URL/api/ci/suite/$PYLEARN_TOKEN" -o .pylearn/suite.json
          python -c "import json,pathlib;s=json.loads(pathlib.Path('.pylearn/suite.json').read_text());[(pathlib.Path('.pylearn',p).parent.mkdir(parents=True,exist_ok=True),pathlib.Path('.pylearn',p).write_text(c)) for p,c in s['files'].items()];pathlib.Path('.pylearn/requirements.txt').write_text(chr(10).join(s['requirements'])+chr(10))"
          uv pip install -r .pylearn/requirements.txt
      - name: Run the tests
        run: |
          . .venv/bin/activate
          python -m pytest ${PYTEST_ARGS.join(" ")}
      - name: Report to pylearn
        if: always()
        run: |
          . .venv/bin/activate
          python .pylearn/${REPORTER}
`;
}

/** Equal for the purpose of "is this our workflow": line endings and trailing space don't count */
export function sameWorkflow(a: string, b: string): boolean {
  const norm = (s: string) =>
    s
      .replace(/\r\n/g, "\n")
      .split("\n")
      .map((l) => l.trimEnd())
      .join("\n")
      .trim();
  return norm(a) === norm(b);
}
