type LessonContentInput = {
  moduleTitle: string;
  title: string;
  description: string;
  content: string;
};

type LessonOverride = {
  content?: string;
  estimatedTime?: number;
};

const lessonOverrides: Record<string, LessonOverride> = {
  "Python Setup & Fundamentals::Setting Up Python": {
    estimatedTime: 20,
    content: [
      "# Setting Up Python",
      "",
      "## Why this matters",
      "",
      "Before you can write Python confidently, you need a setup that feels smooth and predictable. This lesson walks through installing Python, verifying the install, creating isolated environments, and setting up a comfortable editor.",
      "",
      "## What you will learn",
      "",
      "- How to install Python on Windows, macOS, and Linux",
      "- How to verify that Python and pip are available",
      "- Why virtual environments matter",
      "- How Python setup compares to Node.js setup",
      "- A simple checklist for getting ready to code",
      "",
      "## Install Python",
      "",
      "### Windows",
      "",
      "1. Download the latest stable Python installer from the official Python website.",
      "2. Run the installer and make sure Add Python to PATH is checked.",
      "3. Finish the install, then open PowerShell and run:",
      "",
      "~~~bash",
      "python --version",
      "pip --version",
      "~~~",
      "",
      "### macOS",
      "",
      "1. Install Python using the official installer or a package manager such as Homebrew.",
      "2. Verify the install in Terminal:",
      "",
      "~~~bash",
      "python3 --version",
      "pip3 --version",
      "~~~",
      "",
      "### Linux",
      "",
      "1. Use your distribution package manager or install from python.org.",
      "2. Verify the install:",
      "",
      "~~~bash",
      "python3 --version",
      "pip3 --version",
      "~~~",
      "",
      "## Create a virtual environment",
      "",
      "Virtual environments keep project dependencies isolated, similar to having a dedicated project folder per app.",
      "",
      "~~~bash",
      "python -m venv .venv",
      "~~~",
      "",
      "Activate it:",
      "",
      "~~~bash",
      "# Windows",
      ".venv\\Scripts\\activate",
      "",
      "# macOS / Linux",
      "source .venv/bin/activate",
      "~~~",
      "",
      "Then upgrade pip:",
      "",
      "~~~bash",
      "python -m pip install --upgrade pip",
      "~~~",
      "",
      "## Choose an editor",
      "",
      "### VS Code",
      "",
      "VS Code is a great default for Python learners:",
      "",
      "- Install the Python extension",
      "- Select the interpreter from the .venv environment",
      "- Enable linting and formatting",
      "",
      "### PyCharm",
      "",
      "PyCharm is also excellent if you want a more opinionated Python experience out of the box.",
      "",
      "## Python vs Node.js setup",
      "",
      "| Task | Python | Node.js |",
      "| --- | --- | --- |",
      "| Install runtime | Python installer | Node installer |",
      "| Package manager | pip | npm / pnpm |",
      "| Project isolation | venv | node_modules |",
      "| Locking dependencies | requirements.txt / pyproject.toml | package-lock.json / pnpm-lock.yaml |",
      "",
      "## Common pitfalls",
      "",
      "- Forgetting to activate the virtual environment before installing packages",
      "- Mixing system Python with project Python",
      "- Not checking that python or python3 points to the expected interpreter",
      "- Skipping PATH setup on Windows",
      "",
      "## Quick practice",
      "",
      "1. Install Python.",
      "2. Verify python --version.",
      "3. Create .venv.",
      "4. Activate it.",
      "5. Confirm pip works inside the environment.",
      "",
      "## Takeaway",
      "",
      "If your setup is clean, the rest of the course becomes much easier. Think of this as the Python equivalent of making sure your Next.js dev environment is working before you start building features.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Python Syntax Basics": {
    estimatedTime: 25,
    content: [
      "# Python Syntax Basics",
      "",
      "## Why this matters",
      "",
      "This is where Python starts to feel familiar. You already know the concepts from JavaScript, so the main job here is to map syntax, naming, and type behavior onto what you already understand.",
      "",
      "## Variables and data types",
      "",
      "Python uses dynamic typing, which means the variable name does not declare the type upfront.",
      "",
      "~~~python",
      "name = 'Ada'",
      "age = 30",
      "is_active = True",
      "balance = 99.95",
      "favorite_language = None",
      "~~~",
      "",
      "Think of this as similar to JavaScript let declarations, but without needing a keyword like const or let for every assignment.",
      "",
      "## Core types",
      "",
      "- int for whole numbers",
      "- float for decimal numbers",
      "- str for text",
      "- bool for true or false",
      "- None for no value",
      "",
      "## Operators",
      "",
      "Python has the same arithmetic and comparison operators you already know:",
      "",
      "~~~python",
      "total = 10 + 5",
      "remaining = 10 - 5",
      "product = 10 * 5",
      "ratio = 10 / 5",
      "is_equal = 10 == 5",
      "is_greater = 10 > 5",
      "~~~",
      "",
      "One difference to remember: division always returns a float, even when the result looks like a whole number.",
      "",
      "## Type conversion",
      "",
      "Python is explicit when converting between types.",
      "",
      "~~~python",
      "count = int('42')",
      "price = float('19.99')",
      "is_ready = bool(1)",
      "message = str(123)",
      "~~~",
      "",
      "## Truthiness",
      "",
      "Falsy values are similar to JavaScript, but Python has its own rules.",
      "",
      "Falsy examples include:",
      "",
      "- False",
      "- 0",
      "- 0.0",
      "- empty string",
      "- empty list",
      "- empty tuple",
      "- None",
      "",
      "## Naming conventions",
      "",
      "Python prefers snake_case for variables and functions, which is one of the biggest style shifts for JavaScript developers.",
      "",
      "~~~python",
      "first_name = 'Grace'",
      "total_score = 100",
      "def calculate_tax(amount):",
      "    return amount * 0.15",
      "~~~",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Variable declaration | name = value | let name = value |",
      "| Equality | == and != | ==, ===, !=, !== |",
      "| Text | str | string |",
      "| No value | None | null / undefined |",
      "| Naming style | snake_case | camelCase |",
      "",
      "## Quick practice",
      "",
      "1. Create variables for your name, age, and favorite framework.",
      "2. Convert a string number to an integer.",
      "3. Test a value for truthiness.",
      "4. Compare two values with == and >.",
      "",
      "## Takeaway",
      "",
      "Python syntax is intentionally readable. Once you get comfortable with assignment, types, and operators, you can focus on solving problems instead of fighting the language.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Working with Strings": {
    estimatedTime: 20,
    content: [
      "# Working with Strings",
      "",
      "## Why this matters",
      "",
      "Strings are everywhere in real programs: file paths, user input, API data, and formatted output. This lesson gives you the string tools you will use constantly in Python.",
      "",
      "## String basics",
      "",
      "Python strings can use single quotes, double quotes, or triple quotes for multiline text.",
      "",
      "~~~python",
      "single = 'hello'",
      'double = "world"',
      "multiline = '''Line one",
      "Line two'''",
      "~~~",
      "",
      "## Common methods",
      "",
      "- upper and lower for case changes",
      "- strip for trimming whitespace",
      "- find for searching",
      "- replace for substitutions",
      "- split for breaking text into parts",
      "- join for combining lists into text",
      "",
      "~~~python",
      "message = '  Python is fun  '",
      "clean = message.strip()",
      "upper = clean.upper()",
      "parts = 'apple,banana,pear'.split(',')",
      "combined = ' | '.join(parts)",
      "~~~",
      "",
      "## Indexing and slicing",
      "",
      "Python uses zero-based indexing and supports slicing with start, stop, and step.",
      "",
      "~~~python",
      "language = 'Python'",
      "first = language[0]",
      "last = language[-1]",
      "slice_one = language[0:3]",
      "reverse = language[::-1]",
      "~~~",
      "",
      "## Formatting strings",
      "",
      "Formatted strings are Python's answer to template literals.",
      "",
      "~~~python",
      "name = 'Ada'",
      "score = 98",
      "summary = f'{name} scored {score} points'",
      "~~~",
      "",
      "Use f-strings whenever you want readable inline formatting.",
      "",
      "## Raw strings",
      "",
      "Raw strings help with file paths and regular expressions by reducing escape noise.",
      "",
      "~~~python",
      "path = r'C:\\Users\\rezee\\notes.txt'",
      "pattern = r'\\d+'",
      "~~~",
      "",
      "## Python versus JavaScript strings",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Interpolation | f'{name}' | `${name}` |",
      "| Trimming | strip | trim |",
      "| Search | find | indexOf / includes |",
      "| Split | split | split |",
      "| Join | join | join |",
      "",
      "## Quick practice",
      "",
      "1. Trim a user-entered string.",
      "2. Convert it to uppercase.",
      "3. Slice the first three characters.",
      "4. Build a formatted sentence with an f-string.",
      "",
      "## Takeaway",
      "",
      "Strings are one of Python's most pleasant features. Once formatting and slicing feel natural, the rest of the language becomes much easier to work with.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Input and Output": {
    estimatedTime: 15,
    content: [
      "# Input and Output",
      "",
      "## Why this matters",
      "",
      "This lesson turns Python from a language you read into a language you can interact with. You will learn how to display information, collect input, and work with command line arguments.",
      "",
      "## Output with print",
      "",
      "The print function is the simplest way to send text to the terminal.",
      "",
      "~~~python",
      "print('Hello, Python!')",
      "print('Total:', 42)",
      "~~~",
      "",
      "## Input from the user",
      "",
      "The input function pauses execution and waits for text from the keyboard.",
      "",
      "~~~python",
      "name = input('What is your name? ')",
      "print(f'Welcome, {name}!')",
      "~~~",
      "",
      "If you need numbers, convert the input after reading it.",
      "",
      "~~~python",
      "age = int(input('How old are you? '))",
      "print(f'Next year you will be {age + 1}')",
      "~~~",
      "",
      "## Basic validation",
      "",
      "User input is always a string, so simple checks go a long way.",
      "",
      "~~~python",
      "raw_value = input('Enter a number: ')",
      "if raw_value.isdigit():",
      "    value = int(raw_value)",
      "    print(value * 2)",
      "else:",
      "    print('Please enter a whole number.')",
      "~~~",
      "",
      "## Command line arguments",
      "",
      "Python can read arguments passed directly to the script.",
      "",
      "~~~python",
      "import sys",
      "",
      "print(sys.argv)",
      "~~~",
      "",
      "This is especially useful for small tools and scripts, just like process arguments in Node.js.",
      "",
      "## Basic file I/O",
      "",
      "You do not need to master file handling yet, but it helps to see the shape of it early.",
      "",
      "~~~python",
      "with open('notes.txt', 'r', encoding='utf-8') as file:",
      "    text = file.read()",
      "    print(text)",
      "~~~",
      "",
      "## Mini workflow",
      "",
      "1. Ask the user for a name.",
      "2. Ask for a favorite number.",
      "3. Print a personalized message.",
      "4. Read one argument from the command line.",
      "5. Try reading a small text file.",
      "",
      "## Takeaway",
      "",
      "Input and output are the bridge between your code and the outside world. Once this lesson feels comfortable, simple Python scripts start feeling useful immediately.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Lists and Tuples": {
    estimatedTime: 30,
    content: [
      "# Lists and Tuples",
      "",
      "## Why this matters",
      "",
      "Lists and tuples are the workhorses of Python data handling. If you come from JavaScript, lists feel like arrays, but tuples introduce the idea of fixed-size, immutable grouped data.",
      "",
      "## Lists",
      "",
      "Lists are ordered, mutable collections.",
      "",
      "~~~python",
      "fruits = ['apple', 'banana', 'pear']",
      "fruits.append('mango')",
      "fruits[0] = 'orange'",
      "~~~",
      "",
      "Useful list operations include append, insert, remove, pop, sort, and reverse.",
      "",
      "## Indexing and slicing",
      "",
      "~~~python",
      "numbers = [10, 20, 30, 40, 50]",
      "first = numbers[0]",
      "last_two = numbers[-2:]",
      "middle = numbers[1:4]",
      "~~~",
      "",
      "Slicing is one of the most practical Python features because it makes subsetting data very readable.",
      "",
      "## Tuples",
      "",
      "Tuples are ordered and immutable. Once created, they are meant to stay the same.",
      "",
      "~~~python",
      "point = (10, 20)",
      "person = ('Ada', 32, 'Engineer')",
      "x, y = point",
      "~~~",
      "",
      "Tuples are great when you want to represent a fixed group of related values.",
      "",
      "## When to use which",
      "",
      "- Use lists when you need to add, remove, or reorder items",
      "- Use tuples when the shape of the data should stay fixed",
      "",
      "## Python versus JavaScript arrays",
      "",
      "| Concept | Python list or tuple | JavaScript array |",
      "| --- | --- | --- |",
      "| Add item | append | push |",
      "| Remove end item | pop | pop |",
      "| Slice | [start:end] | slice(start, end) |",
      "| Fixed data | tuple | often an array or object |",
      "",
      "## Quick practice",
      "",
      "1. Create a list of your favorite tools.",
      "2. Add one more item to the list.",
      "3. Slice the first two items.",
      "4. Create a tuple for a coordinate.",
      "5. Unpack the tuple into two variables.",
      "",
      "## Takeaway",
      "",
      "Lists and tuples are the foundation for almost every Python program. Once you understand their differences, the rest of the data structure lessons become much easier.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Dictionaries and Sets": {
    estimatedTime: 25,
    content: [
      "# Dictionaries and Sets",
      "",
      "## Why this matters",
      "",
      "Dictionaries and sets solve two different kinds of problems: dictionaries map keys to values, while sets help you work with unique items and fast membership checks.",
      "",
      "## Dictionaries",
      "",
      "A dictionary stores key-value pairs.",
      "",
      "~~~python",
      "profile = {",
      "    'name': 'Ada',",
      "    'role': 'Engineer',",
      "    'active': True,",
      "}",
      "print(profile['name'])",
      "profile['language'] = 'Python'",
      "~~~",
      "",
      "Common methods include keys, values, items, get, update, pop, and clear.",
      "",
      "## Sets",
      "",
      "Sets store unique values and are ideal for deduplication and membership checks.",
      "",
      "~~~python",
      "tags = {'python', 'javascript', 'python'}",
      "print(tags)",
      "tags.add('nextjs')",
      "~~~",
      "",
      "Set operations are especially useful:",
      "",
      "~~~python",
      "a = {'python', 'js', 'sql'}",
      "b = {'python', 'data', 'sql'}",
      "print(a | b)   # union",
      "print(a & b)   # intersection",
      "print(a - b)   # difference",
      "~~~",
      "",
      "## Python versus JavaScript objects and Set",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Key lookup | dict[key] | object[key] |",
      "| Safe lookup | get | optional chaining or fallback |",
      "| Unique collection | set | Set |",
      "| Membership | in | includes / has |",
      "",
      "## Quick practice",
      "",
      "1. Create a dictionary for a book.",
      "2. Add a new field with update syntax.",
      "3. Use get with a fallback value.",
      "4. Create a set of skills without duplicates.",
      "5. Try union and intersection on two sets.",
      "",
      "## Takeaway",
      "",
      "Dictionaries are the default way to model real-world records in Python, and sets are your secret weapon for uniqueness and fast comparisons.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Conditional Logic": {
    estimatedTime: 20,
    content: [
      "# Conditional Logic",
      "",
      "## Why this matters",
      "",
      "Conditionals let your program respond differently depending on what the user does or what the data looks like. This is where Python starts to feel interactive.",
      "",
      "## if, elif, else",
      "",
      "~~~python",
      "score = 87",
      "",
      "if score >= 90:",
      "    grade = 'A'",
      "elif score >= 80:",
      "    grade = 'B'",
      "else:",
      "    grade = 'C'",
      "~~~",
      "",
      "Python uses indentation instead of braces, so the block structure is visible at a glance.",
      "",
      "## Comparison and logical operators",
      "",
      "~~~python",
      "age = 21",
      "has_id = True",
      "",
      "if age >= 18 and has_id:",
      "    print('Welcome in')",
      "~~~",
      "",
      "Common operators include ==, !=, >, <, >=, <=, and, or, not.",
      "",
      "## Truthiness",
      "",
      "Python values can be treated as true or false even when they are not explicitly boolean.",
      "",
      "Falsy values include empty collections, 0, 0.0, None, and False.",
      "",
      "## Ternary expressions",
      "",
      "~~~python",
      "status = 'adult' if age >= 18 else 'minor'",
      "~~~",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| If block | if condition: | if (condition) { |",
      "| Else if | elif | else if |",
      "| Logical and | and | && |",
      "| Logical or | or | || |",
      "| Truthy/falsy | same idea, different details | same idea |",
      "",
      "## Quick practice",
      "",
      "1. Write a grade calculator.",
      "2. Check whether a string is empty before using it.",
      "3. Combine two boolean conditions with and or or.",
      "4. Try a ternary expression for a small decision.",
      "",
      "## Takeaway",
      "",
      "Conditionals are the control center of your program. Once the syntax feels natural, you can build much richer user flows and validation logic.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Loops and Iteration": {
    estimatedTime: 25,
    content: [
      "# Loops and Iteration",
      "",
      "## Why this matters",
      "",
      "Loops let you repeat work without duplicating code. They are essential for menus, data processing, and anything that needs to inspect a collection item by item.",
      "",
      "## for loops",
      "",
      "~~~python",
      "for item in ['a', 'b', 'c']:",
      "    print(item)",
      "~~~",
      "",
      "For loops in Python are about iterating over items, not manually managing indexes.",
      "",
      "## range",
      "",
      "~~~python",
      "for i in range(3):",
      "    print(i)",
      "~~~",
      "",
      "## while loops",
      "",
      "~~~python",
      "count = 0",
      "while count < 3:",
      "    print(count)",
      "    count += 1",
      "~~~",
      "",
      "## Loop control",
      "",
      "- break exits the loop early",
      "- continue skips to the next iteration",
      "- pass is a placeholder",
      "",
      "## enumerate and zip",
      "",
      "~~~python",
      "names = ['Ada', 'Linus', 'Grace']",
      "for index, name in enumerate(names):",
      "    print(index, name)",
      "",
      "left = ['a', 'b']",
      "right = [1, 2]",
      "for pair in zip(left, right):",
      "    print(pair)",
      "~~~",
      "",
      "## Python versus JavaScript loops",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Iterate array | for item in items | for...of |",
      "| Indexed iteration | enumerate | entries or manual index |",
      "| Repeat N times | range(N) | for (let i = 0; i < N; i++) |",
      "| Early exit | break | break |",
      "",
      "## Quick practice",
      "",
      "1. Print the numbers 1 through 5.",
      "2. Iterate over a list of course names.",
      "3. Use enumerate to print both index and value.",
      "4. Write a while loop that stops at a condition.",
      "",
      "## Takeaway",
      "",
      "Python loops are readable and expressive. Once you get comfortable with range, enumerate, and break/continue, many everyday tasks become straightforward.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Comprehensions": {
    estimatedTime: 20,
    content: [
      "# Comprehensions",
      "",
      "## Why this matters",
      "",
      "Comprehensions are Python's shorthand for creating collections. They let you express filtering and transformation in one compact, readable line.",
      "",
      "## List comprehensions",
      "",
      "~~~python",
      "numbers = [1, 2, 3, 4, 5]",
      "squares = [n * n for n in numbers]",
      "even_squares = [n * n for n in numbers if n % 2 == 0]",
      "~~~",
      "",
      "## Dictionary comprehensions",
      "",
      "~~~python",
      "names = ['Ada', 'Grace', 'Linus']",
      "name_lengths = {name: len(name) for name in names}",
      "~~~",
      "",
      "## Set comprehensions",
      "",
      "~~~python",
      "words = ['python', 'Python', 'pYthon']",
      "normalized = {word.lower() for word in words}",
      "~~~",
      "",
      "## Nested comprehensions",
      "",
      "~~~python",
      "grid = [[row * col for col in range(3)] for row in range(3)]",
      "~~~",
      "",
      "Comprehensions can replace small map and filter chains from JavaScript when the transformation is simple enough to stay readable.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Map style | [f(x) for x in items] | items.map(f) |",
      "| Filter style | [x for x in items if ...] | items.filter(...) |",
      "| Unique values | {x for x in items} | new Set(items) |",
      "",
      "## Quick practice",
      "",
      "1. Build a list of doubled numbers.",
      "2. Filter the even numbers.",
      "3. Create a dictionary that maps names to lengths.",
      "4. Convert a list of strings to lowercase with a set comprehension.",
      "",
      "## Takeaway",
      "",
      "Comprehensions are one of the cleanest ways to write small data transformations in Python. Learn them early and they will save you a lot of boilerplate.",
    ].join("\n"),
  },
};

export function getLessonContent({
  moduleTitle,
  title,
  description,
  content,
}: LessonContentInput): string {
  const key = `${moduleTitle}::${title}`;
  const override = lessonOverrides[key]?.content;
  if (!override) return content;

  const wordCount = content.trim().split(/\s+/).filter(Boolean).length;
  if (wordCount >= 40) return content;

  return override || `${description}\n\n${content}`;
}

export function getLessonEstimatedTime(
  moduleTitle: string,
  title: string,
  fallback: number
): number {
  const key = `${moduleTitle}::${title}`;
  return lessonOverrides[key]?.estimatedTime ?? fallback;
}
