type LessonContentInput = {
  moduleTitle: string;
  title: string;
  description: string;
  content: string;
};

type LessonOverride = {
  content?: string;
  estimatedTime?: number;
};

const lessonOverrides: Record<string, LessonOverride> = {
  "Python Setup & Fundamentals::Setting Up Python": {
    estimatedTime: 20,
    content: [
      "# Setting Up Python",
      "",
      "## Why this matters",
      "",
      "Before you can write Python confidently, you need a setup that feels smooth and predictable. This lesson walks through installing Python, verifying the install, creating isolated environments, and setting up a comfortable editor.",
      "",
      "## What you will learn",
      "",
      "- How to install Python on Windows, macOS, and Linux",
      "- How to verify that Python and pip are available",
      "- Why virtual environments matter",
      "- How Python setup compares to Node.js setup",
      "- A simple checklist for getting ready to code",
      "",
      "## Install Python",
      "",
      "### Windows",
      "",
      "1. Download the latest stable Python installer from the official Python website.",
      "2. Run the installer and make sure Add Python to PATH is checked.",
      "3. Finish the install, then open PowerShell and run:",
      "",
      "~~~bash",
      "python --version",
      "pip --version",
      "~~~",
      "",
      "### macOS",
      "",
      "1. Install Python using the official installer or a package manager such as Homebrew.",
      "2. Verify the install in Terminal:",
      "",
      "~~~bash",
      "python3 --version",
      "pip3 --version",
      "~~~",
      "",
      "### Linux",
      "",
      "1. Use your distribution package manager or install from python.org.",
      "2. Verify the install:",
      "",
      "~~~bash",
      "python3 --version",
      "pip3 --version",
      "~~~",
      "",
      "## Create a virtual environment",
      "",
      "Virtual environments keep project dependencies isolated, similar to having a dedicated project folder per app.",
      "",
      "~~~bash",
      "python -m venv .venv",
      "~~~",
      "",
      "Activate it:",
      "",
      "~~~bash",
      "# Windows",
      ".venv\\Scripts\\activate",
      "",
      "# macOS / Linux",
      "source .venv/bin/activate",
      "~~~",
      "",
      "Then upgrade pip:",
      "",
      "~~~bash",
      "python -m pip install --upgrade pip",
      "~~~",
      "",
      "## Choose an editor",
      "",
      "### VS Code",
      "",
      "VS Code is a great default for Python learners:",
      "",
      "- Install the Python extension",
      "- Select the interpreter from the .venv environment",
      "- Enable linting and formatting",
      "",
      "### PyCharm",
      "",
      "PyCharm is also excellent if you want a more opinionated Python experience out of the box.",
      "",
      "## Python vs Node.js setup",
      "",
      "| Task | Python | Node.js |",
      "| --- | --- | --- |",
      "| Install runtime | Python installer | Node installer |",
      "| Package manager | pip | npm / pnpm |",
      "| Project isolation | venv | node_modules |",
      "| Locking dependencies | requirements.txt / pyproject.toml | package-lock.json / pnpm-lock.yaml |",
      "",
      "## Common pitfalls",
      "",
      "- Forgetting to activate the virtual environment before installing packages",
      "- Mixing system Python with project Python",
      "- Not checking that python or python3 points to the expected interpreter",
      "- Skipping PATH setup on Windows",
      "",
      "## Quick practice",
      "",
      "1. Install Python.",
      "2. Verify python --version.",
      "3. Create .venv.",
      "4. Activate it.",
      "5. Confirm pip works inside the environment.",
      "",
      "## Takeaway",
      "",
      "If your setup is clean, the rest of the course becomes much easier. Think of this as the Python equivalent of making sure your Next.js dev environment is working before you start building features.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Python Syntax Basics": {
    estimatedTime: 25,
    content: [
      "# Python Syntax Basics",
      "",
      "## Why this matters",
      "",
      "This is where Python starts to feel familiar. You already know the concepts from JavaScript, so the main job here is to map syntax, naming, and type behavior onto what you already understand.",
      "",
      "## Variables and data types",
      "",
      "Python uses dynamic typing, which means the variable name does not declare the type upfront.",
      "",
      "~~~python",
      "name = 'Ada'",
      "age = 30",
      "is_active = True",
      "balance = 99.95",
      "favorite_language = None",
      "~~~",
      "",
      "Think of this as similar to JavaScript let declarations, but without needing a keyword like const or let for every assignment.",
      "",
      "## Core types",
      "",
      "- int for whole numbers",
      "- float for decimal numbers",
      "- str for text",
      "- bool for true or false",
      "- None for no value",
      "",
      "## Operators",
      "",
      "Python has the same arithmetic and comparison operators you already know:",
      "",
      "~~~python",
      "total = 10 + 5",
      "remaining = 10 - 5",
      "product = 10 * 5",
      "ratio = 10 / 5",
      "is_equal = 10 == 5",
      "is_greater = 10 > 5",
      "~~~",
      "",
      "One difference to remember: division always returns a float, even when the result looks like a whole number.",
      "",
      "## Type conversion",
      "",
      "Python is explicit when converting between types.",
      "",
      "~~~python",
      "count = int('42')",
      "price = float('19.99')",
      "is_ready = bool(1)",
      "message = str(123)",
      "~~~",
      "",
      "## Truthiness",
      "",
      "Falsy values are similar to JavaScript, but Python has its own rules.",
      "",
      "Falsy examples include:",
      "",
      "- False",
      "- 0",
      "- 0.0",
      "- empty string",
      "- empty list",
      "- empty tuple",
      "- None",
      "",
      "## Naming conventions",
      "",
      "Python prefers snake_case for variables and functions, which is one of the biggest style shifts for JavaScript developers.",
      "",
      "~~~python",
      "first_name = 'Grace'",
      "total_score = 100",
      "def calculate_tax(amount):",
      "    return amount * 0.15",
      "~~~",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Variable declaration | name = value | let name = value |",
      "| Equality | == and != | ==, ===, !=, !== |",
      "| Text | str | string |",
      "| No value | None | null / undefined |",
      "| Naming style | snake_case | camelCase |",
      "",
      "## Quick practice",
      "",
      "1. Create variables for your name, age, and favorite framework.",
      "2. Convert a string number to an integer.",
      "3. Test a value for truthiness.",
      "4. Compare two values with == and >.",
      "",
      "## Takeaway",
      "",
      "Python syntax is intentionally readable. Once you get comfortable with assignment, types, and operators, you can focus on solving problems instead of fighting the language.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Working with Strings": {
    estimatedTime: 20,
    content: [
      "# Working with Strings",
      "",
      "## Why this matters",
      "",
      "Strings are everywhere in real programs: file paths, user input, API data, and formatted output. This lesson gives you the string tools you will use constantly in Python.",
      "",
      "## String basics",
      "",
      "Python strings can use single quotes, double quotes, or triple quotes for multiline text.",
      "",
      "~~~python",
      "single = 'hello'",
      'double = "world"',
      "multiline = '''Line one",
      "Line two'''",
      "~~~",
      "",
      "## Common methods",
      "",
      "- upper and lower for case changes",
      "- strip for trimming whitespace",
      "- find for searching",
      "- replace for substitutions",
      "- split for breaking text into parts",
      "- join for combining lists into text",
      "",
      "~~~python",
      "message = '  Python is fun  '",
      "clean = message.strip()",
      "upper = clean.upper()",
      "parts = 'apple,banana,pear'.split(',')",
      "combined = ' | '.join(parts)",
      "~~~",
      "",
      "## Indexing and slicing",
      "",
      "Python uses zero-based indexing and supports slicing with start, stop, and step.",
      "",
      "~~~python",
      "language = 'Python'",
      "first = language[0]",
      "last = language[-1]",
      "slice_one = language[0:3]",
      "reverse = language[::-1]",
      "~~~",
      "",
      "## Formatting strings",
      "",
      "Formatted strings are Python's answer to template literals.",
      "",
      "~~~python",
      "name = 'Ada'",
      "score = 98",
      "summary = f'{name} scored {score} points'",
      "~~~",
      "",
      "Use f-strings whenever you want readable inline formatting.",
      "",
      "## Raw strings",
      "",
      "Raw strings help with file paths and regular expressions by reducing escape noise.",
      "",
      "~~~python",
      "path = r'C:\\Users\\rezee\\notes.txt'",
      "pattern = r'\\d+'",
      "~~~",
      "",
      "## Python versus JavaScript strings",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Interpolation | f'{name}' | `${name}` |",
      "| Trimming | strip | trim |",
      "| Search | find | indexOf / includes |",
      "| Split | split | split |",
      "| Join | join | join |",
      "",
      "## Quick practice",
      "",
      "1. Trim a user-entered string.",
      "2. Convert it to uppercase.",
      "3. Slice the first three characters.",
      "4. Build a formatted sentence with an f-string.",
      "",
      "## Takeaway",
      "",
      "Strings are one of Python's most pleasant features. Once formatting and slicing feel natural, the rest of the language becomes much easier to work with.",
    ].join("\n"),
  },
  "Python Setup & Fundamentals::Input and Output": {
    estimatedTime: 15,
    content: [
      "# Input and Output",
      "",
      "## Why this matters",
      "",
      "This lesson turns Python from a language you read into a language you can interact with. You will learn how to display information, collect input, and work with command line arguments.",
      "",
      "## Output with print",
      "",
      "The print function is the simplest way to send text to the terminal.",
      "",
      "~~~python",
      "print('Hello, Python!')",
      "print('Total:', 42)",
      "~~~",
      "",
      "## Input from the user",
      "",
      "The input function pauses execution and waits for text from the keyboard.",
      "",
      "~~~python",
      "name = input('What is your name? ')",
      "print(f'Welcome, {name}!')",
      "~~~",
      "",
      "If you need numbers, convert the input after reading it.",
      "",
      "~~~python",
      "age = int(input('How old are you? '))",
      "print(f'Next year you will be {age + 1}')",
      "~~~",
      "",
      "## Basic validation",
      "",
      "User input is always a string, so simple checks go a long way.",
      "",
      "~~~python",
      "raw_value = input('Enter a number: ')",
      "if raw_value.isdigit():",
      "    value = int(raw_value)",
      "    print(value * 2)",
      "else:",
      "    print('Please enter a whole number.')",
      "~~~",
      "",
      "## Command line arguments",
      "",
      "Python can read arguments passed directly to the script.",
      "",
      "~~~python",
      "import sys",
      "",
      "print(sys.argv)",
      "~~~",
      "",
      "This is especially useful for small tools and scripts, just like process arguments in Node.js.",
      "",
      "## Basic file I/O",
      "",
      "You do not need to master file handling yet, but it helps to see the shape of it early.",
      "",
      "~~~python",
      "with open('notes.txt', 'r', encoding='utf-8') as file:",
      "    text = file.read()",
      "    print(text)",
      "~~~",
      "",
      "## Mini workflow",
      "",
      "1. Ask the user for a name.",
      "2. Ask for a favorite number.",
      "3. Print a personalized message.",
      "4. Read one argument from the command line.",
      "5. Try reading a small text file.",
      "",
      "## Takeaway",
      "",
      "Input and output are the bridge between your code and the outside world. Once this lesson feels comfortable, simple Python scripts start feeling useful immediately.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Lists and Tuples": {
    estimatedTime: 30,
    content: [
      "# Lists and Tuples",
      "",
      "## Why this matters",
      "",
      "Lists and tuples are the workhorses of Python data handling. If you come from JavaScript, lists feel like arrays, but tuples introduce the idea of fixed-size, immutable grouped data.",
      "",
      "## Lists",
      "",
      "Lists are ordered, mutable collections.",
      "",
      "~~~python",
      "fruits = ['apple', 'banana', 'pear']",
      "fruits.append('mango')",
      "fruits[0] = 'orange'",
      "~~~",
      "",
      "Useful list operations include append, insert, remove, pop, sort, and reverse.",
      "",
      "## Indexing and slicing",
      "",
      "~~~python",
      "numbers = [10, 20, 30, 40, 50]",
      "first = numbers[0]",
      "last_two = numbers[-2:]",
      "middle = numbers[1:4]",
      "~~~",
      "",
      "Slicing is one of the most practical Python features because it makes subsetting data very readable.",
      "",
      "## Tuples",
      "",
      "Tuples are ordered and immutable. Once created, they are meant to stay the same.",
      "",
      "~~~python",
      "point = (10, 20)",
      "person = ('Ada', 32, 'Engineer')",
      "x, y = point",
      "~~~",
      "",
      "Tuples are great when you want to represent a fixed group of related values.",
      "",
      "## When to use which",
      "",
      "- Use lists when you need to add, remove, or reorder items",
      "- Use tuples when the shape of the data should stay fixed",
      "",
      "## Python versus JavaScript arrays",
      "",
      "| Concept | Python list or tuple | JavaScript array |",
      "| --- | --- | --- |",
      "| Add item | append | push |",
      "| Remove end item | pop | pop |",
      "| Slice | [start:end] | slice(start, end) |",
      "| Fixed data | tuple | often an array or object |",
      "",
      "## Quick practice",
      "",
      "1. Create a list of your favorite tools.",
      "2. Add one more item to the list.",
      "3. Slice the first two items.",
      "4. Create a tuple for a coordinate.",
      "5. Unpack the tuple into two variables.",
      "",
      "## Takeaway",
      "",
      "Lists and tuples are the foundation for almost every Python program. Once you understand their differences, the rest of the data structure lessons become much easier.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Dictionaries and Sets": {
    estimatedTime: 25,
    content: [
      "# Dictionaries and Sets",
      "",
      "## Why this matters",
      "",
      "Dictionaries and sets solve two different kinds of problems: dictionaries map keys to values, while sets help you work with unique items and fast membership checks.",
      "",
      "## Dictionaries",
      "",
      "A dictionary stores key-value pairs.",
      "",
      "~~~python",
      "profile = {",
      "    'name': 'Ada',",
      "    'role': 'Engineer',",
      "    'active': True,",
      "}",
      "print(profile['name'])",
      "profile['language'] = 'Python'",
      "~~~",
      "",
      "Common methods include keys, values, items, get, update, pop, and clear.",
      "",
      "## Sets",
      "",
      "Sets store unique values and are ideal for deduplication and membership checks.",
      "",
      "~~~python",
      "tags = {'python', 'javascript', 'python'}",
      "print(tags)",
      "tags.add('nextjs')",
      "~~~",
      "",
      "Set operations are especially useful:",
      "",
      "~~~python",
      "a = {'python', 'js', 'sql'}",
      "b = {'python', 'data', 'sql'}",
      "print(a | b)   # union",
      "print(a & b)   # intersection",
      "print(a - b)   # difference",
      "~~~",
      "",
      "## Python versus JavaScript objects and Set",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Key lookup | dict[key] | object[key] |",
      "| Safe lookup | get | optional chaining or fallback |",
      "| Unique collection | set | Set |",
      "| Membership | in | includes / has |",
      "",
      "## Quick practice",
      "",
      "1. Create a dictionary for a book.",
      "2. Add a new field with update syntax.",
      "3. Use get with a fallback value.",
      "4. Create a set of skills without duplicates.",
      "5. Try union and intersection on two sets.",
      "",
      "## Takeaway",
      "",
      "Dictionaries are the default way to model real-world records in Python, and sets are your secret weapon for uniqueness and fast comparisons.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Conditional Logic": {
    estimatedTime: 20,
    content: [
      "# Conditional Logic",
      "",
      "## Why this matters",
      "",
      "Conditionals let your program respond differently depending on what the user does or what the data looks like. This is where Python starts to feel interactive.",
      "",
      "## if, elif, else",
      "",
      "~~~python",
      "score = 87",
      "",
      "if score >= 90:",
      "    grade = 'A'",
      "elif score >= 80:",
      "    grade = 'B'",
      "else:",
      "    grade = 'C'",
      "~~~",
      "",
      "Python uses indentation instead of braces, so the block structure is visible at a glance.",
      "",
      "## Comparison and logical operators",
      "",
      "~~~python",
      "age = 21",
      "has_id = True",
      "",
      "if age >= 18 and has_id:",
      "    print('Welcome in')",
      "~~~",
      "",
      "Common operators include ==, !=, >, <, >=, <=, and, or, not.",
      "",
      "## Truthiness",
      "",
      "Python values can be treated as true or false even when they are not explicitly boolean.",
      "",
      "Falsy values include empty collections, 0, 0.0, None, and False.",
      "",
      "## Ternary expressions",
      "",
      "~~~python",
      "status = 'adult' if age >= 18 else 'minor'",
      "~~~",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| If block | if condition: | if (condition) { |",
      "| Else if | elif | else if |",
      "| Logical and | and | && |",
      "| Logical or | or | || |",
      "| Truthy/falsy | same idea, different details | same idea |",
      "",
      "## Quick practice",
      "",
      "1. Write a grade calculator.",
      "2. Check whether a string is empty before using it.",
      "3. Combine two boolean conditions with and or or.",
      "4. Try a ternary expression for a small decision.",
      "",
      "## Takeaway",
      "",
      "Conditionals are the control center of your program. Once the syntax feels natural, you can build much richer user flows and validation logic.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Loops and Iteration": {
    estimatedTime: 25,
    content: [
      "# Loops and Iteration",
      "",
      "## Why this matters",
      "",
      "Loops let you repeat work without duplicating code. They are essential for menus, data processing, and anything that needs to inspect a collection item by item.",
      "",
      "## for loops",
      "",
      "~~~python",
      "for item in ['a', 'b', 'c']:",
      "    print(item)",
      "~~~",
      "",
      "For loops in Python are about iterating over items, not manually managing indexes.",
      "",
      "## range",
      "",
      "~~~python",
      "for i in range(3):",
      "    print(i)",
      "~~~",
      "",
      "## while loops",
      "",
      "~~~python",
      "count = 0",
      "while count < 3:",
      "    print(count)",
      "    count += 1",
      "~~~",
      "",
      "## Loop control",
      "",
      "- break exits the loop early",
      "- continue skips to the next iteration",
      "- pass is a placeholder",
      "",
      "## enumerate and zip",
      "",
      "~~~python",
      "names = ['Ada', 'Linus', 'Grace']",
      "for index, name in enumerate(names):",
      "    print(index, name)",
      "",
      "left = ['a', 'b']",
      "right = [1, 2]",
      "for pair in zip(left, right):",
      "    print(pair)",
      "~~~",
      "",
      "## Python versus JavaScript loops",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Iterate array | for item in items | for...of |",
      "| Indexed iteration | enumerate | entries or manual index |",
      "| Repeat N times | range(N) | for (let i = 0; i < N; i++) |",
      "| Early exit | break | break |",
      "",
      "## Quick practice",
      "",
      "1. Print the numbers 1 through 5.",
      "2. Iterate over a list of course names.",
      "3. Use enumerate to print both index and value.",
      "4. Write a while loop that stops at a condition.",
      "",
      "## Takeaway",
      "",
      "Python loops are readable and expressive. Once you get comfortable with range, enumerate, and break/continue, many everyday tasks become straightforward.",
    ].join("\n"),
  },
  "Data Structures & Control Flow::Comprehensions": {
    estimatedTime: 20,
    content: [
      "# Comprehensions",
      "",
      "## Why this matters",
      "",
      "Comprehensions are Python's shorthand for creating collections. They let you express filtering and transformation in one compact, readable line.",
      "",
      "## List comprehensions",
      "",
      "~~~python",
      "numbers = [1, 2, 3, 4, 5]",
      "squares = [n * n for n in numbers]",
      "even_squares = [n * n for n in numbers if n % 2 == 0]",
      "~~~",
      "",
      "## Dictionary comprehensions",
      "",
      "~~~python",
      "names = ['Ada', 'Grace', 'Linus']",
      "name_lengths = {name: len(name) for name in names}",
      "~~~",
      "",
      "## Set comprehensions",
      "",
      "~~~python",
      "words = ['python', 'Python', 'pYthon']",
      "normalized = {word.lower() for word in words}",
      "~~~",
      "",
      "## Nested comprehensions",
      "",
      "~~~python",
      "grid = [[row * col for col in range(3)] for row in range(3)]",
      "~~~",
      "",
      "Comprehensions can replace small map and filter chains from JavaScript when the transformation is simple enough to stay readable.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Map style | [f(x) for x in items] | items.map(f) |",
      "| Filter style | [x for x in items if ...] | items.filter(...) |",
      "| Unique values | {x for x in items} | new Set(items) |",
      "",
      "## Quick practice",
      "",
      "1. Build a list of doubled numbers.",
      "2. Filter the even numbers.",
      "3. Create a dictionary that maps names to lengths.",
      "4. Convert a list of strings to lowercase with a set comprehension.",
      "",
      "## Takeaway",
      "",
      "Comprehensions are one of the cleanest ways to write small data transformations in Python. Learn them early and they will save you a lot of boilerplate.",
    ].join("\n"),
  },
  "Functions & Modules::Defining Functions": {
    estimatedTime: 25,
    content: [
      "# Defining Functions",
      "",
      "## Why this matters",
      "",
      "Functions are how you turn repeated logic into reusable building blocks. If you already know JavaScript, this lesson helps you map that mental model onto Python's syntax and style.",
      "",
      "## Defining a function",
      "",
      "~~~python",
      "def greet(name):",
      "    return f'Hello, {name}!'",
      "~~~",
      "",
      "A function starts with def, followed by the name, parameters, and a colon. The body is defined by indentation.",
      "",
      "## Calling functions",
      "",
      "~~~python",
      "message = greet('Ada')",
      "print(message)",
      "~~~",
      "",
      "## Return values",
      "",
      "Functions can return any Python value, including tuples.",
      "",
      "~~~python",
      "def get_dimensions():",
      "    return 1920, 1080",
      "",
      "width, height = get_dimensions()",
      "~~~",
      "",
      "## Docstrings",
      "",
      "Docstrings explain what a function does and are part of Python's culture of readable code.",
      "",
      "~~~python",
      "def add(a, b):",
      '    """Return the sum of two numbers."""',
      "    return a + b",
      "~~~",
      "",
      "## Default and keyword arguments",
      "",
      "~~~python",
      "def greet_user(name, greeting='Hello'):",
      "    return f'{greeting}, {name}!'",
      "~~~",
      "",
      "## Python versus JavaScript functions",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Define | def name(): | function name() {} |",
      "| Anonymous | lambda | arrow function |",
      "| Return multiple values | tuple | array or object |",
      "| Documentation | docstring | JSDoc |",
      "",
      "## Quick practice",
      "",
      "1. Write a function that formats a full name.",
      "2. Create a function with a default greeting.",
      "3. Return two values from one function.",
      "4. Add a docstring to each function.",
      "",
      "## Takeaway",
      "",
      "Functions are one of the most important Python habits to build early. Once you are comfortable defining and calling them, your code becomes easier to test, reuse, and organize.",
    ].join("\n"),
  },
  "Functions & Modules::Function Parameters and Returns": {
    estimatedTime: 25,
    content: [
      "# Function Parameters and Returns",
      "",
      "## Why this matters",
      "",
      "Parameters are how functions receive data, and return values are how they hand results back. Once this clicks, you can write much more flexible code.",
      "",
      "## Positional and keyword arguments",
      "",
      "~~~python",
      "def describe_pet(name, species='dog'):",
      "    return f'{name} is a {species}'",
      "",
      "describe_pet('Milo')",
      "describe_pet(name='Pixel', species='cat')",
      "~~~",
      "",
      "## *args and **kwargs",
      "",
      "Use *args when you want any number of positional arguments, and **kwargs for named options.",
      "",
      "~~~python",
      "def total(*numbers):",
      "    return sum(numbers)",
      "",
      "def build_profile(**data):",
      "    return data",
      "~~~",
      "",
      "## Returning multiple values",
      "",
      "~~~python",
      "def split_name(full_name):",
      "    parts = full_name.split()",
      "    return parts[0], parts[-1]",
      "~~~",
      "",
      "## Parameter order",
      "",
      "A common Python pattern is: positional arguments, default arguments, *args, then **kwargs.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Rest args | *args | ...args |",
      "| Keyword args | **kwargs | object destructuring or options object |",
      "| Multiple returns | tuple | array or object |",
      "",
      "## Quick practice",
      "",
      "1. Write a function that accepts a name and an optional title.",
      "2. Sum an arbitrary number of values with *args.",
      "3. Return first and last name from one function.",
      "4. Build a function that accepts an options dictionary.",
      "",
      "## Takeaway",
      "",
      "Flexible function signatures let you build reusable helpers that work across different contexts. That pays off quickly in real code.",
    ].join("\n"),
  },
  "Functions & Modules::Scope and Closures": {
    estimatedTime: 20,
    content: [
      "# Scope and Closures",
      "",
      "## Why this matters",
      "",
      "Scope determines where a variable can be used. Closures let inner functions remember values from an outer function. Together, they explain a lot of Python's behavior.",
      "",
      "## Local and global scope",
      "",
      "~~~python",
      "message = 'outside'",
      "",
      "def show_message():",
      "    inner_message = 'inside'",
      "    print(message)",
      "    print(inner_message)",
      "~~~",
      "",
      "Variables created inside a function are local to that function.",
      "",
      "## global and nonlocal",
      "",
      "Use global sparingly and nonlocal when you need to update a variable in an enclosing function.",
      "",
      "~~~python",
      "def outer():",
      "    count = 0",
      "",
      "    def inner():",
      "        nonlocal count",
      "        count += 1",
      "        return count",
      "",
      "    return inner",
      "~~~",
      "",
      "## Closures",
      "",
      "A closure is a function that carries some of its surrounding state with it.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Local scope | function local | function local |",
      "| Update outer variable | nonlocal | closures with let/const state |",
      "| Global update | global | globalThis or module state |",
      "",
      "## Quick practice",
      "",
      "1. Create a counter function using closures.",
      "2. Try accessing a local variable from outside its function.",
      "3. Use nonlocal to modify an enclosing variable.",
      "4. Compare closure behavior with JavaScript.",
      "",
      "## Takeaway",
      "",
      "Understanding scope and closures helps you write cleaner, more predictable code and avoid common bugs.",
    ].join("\n"),
  },
  "Object-Oriented Programming::Classes and Objects": {
    estimatedTime: 120,
    content: [
      "# Classes and Objects",
      "",
      "## Why this matters",
      "",
      "Object-oriented programming (OOP) lets you model real-world entities as objects with attributes and behaviors. If you've used ES6 classes in JavaScript, Python's class system will feel familiar with some important differences.",
      "",
      "## Creating a class",
      "",
      "~~~python",
      "class Dog:",
      '    """A simple dog class"""',
      "    ",
      "    def __init__(self, name, age):",
      "        self.name = name",
      "        self.age = age",
      "    ",
      "    def bark(self):",
      "        return f'{self.name} says woof!'",
      "~~~",
      "",
      "The `__init__` method is the constructor, called when creating a new object. The `self` parameter refers to the instance itself.",
      "",
      "## Creating objects (instances)",
      "",
      "~~~python",
      "my_dog = Dog('Buddy', 3)",
      "print(my_dog.name)      # Buddy",
      "print(my_dog.bark())    # Buddy says woof!",
      "~~~",
      "",
      "Each object is an independent instance with its own attribute values.",
      "",
      "## Instance vs class attributes",
      "",
      "~~~python",
      "class Dog:",
      "    species = 'Canis familiaris'  # Class attribute (shared)",
      "    ",
      "    def __init__(self, name):",
      "        self.name = name  # Instance attribute (unique per object)",
      "",
      "dog1 = Dog('Max')",
      "dog2 = Dog('Bella')",
      "print(dog1.species)  # Canis familiaris (shared)",
      "print(dog1.name)     # Max (unique)",
      "~~~",
      "",
      "Class attributes are shared across all instances, while instance attributes are unique to each object.",
      "",
      "## Python versus JavaScript classes",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Define class | class Dog: | class Dog { |",
      "| Constructor | __init__(self, ...) | constructor(...) |",
      "| Instance reference | self | this |",
      "| Class attribute | defined in class body | static property |",
      "| Create instance | Dog('Max') | new Dog('Max') |",
      "",
      "## The self parameter",
      "",
      "Every instance method must have `self` as the first parameter. Python automatically passes the instance when you call the method:",
      "",
      "~~~python",
      "my_dog.bark()  # Python internally calls: Dog.bark(my_dog)",
      "~~~",
      "",
      "This is similar to JavaScript's `this`, but it's explicit in Python.",
      "",
      "## Quick practice",
      "",
      "1. Create a Person class with name and age attributes",
      "2. Add an introduce() method that returns a greeting",
      "3. Create multiple Person instances",
      "4. Add a class attribute for species",
      "5. Compare with how you'd write this in JavaScript",
      "",
      "## Takeaway",
      "",
      "Python classes provide a clean way to bundle data and functionality. The explicit `self` parameter makes instance methods clear, and the `__init__` constructor sets up new objects. This foundation prepares you for inheritance, polymorphism, and advanced OOP patterns.",
    ].join("\n"),
  },
  "Object-Oriented Programming::Methods and Attributes": {
    estimatedTime: 105,
    content: [
      "# Methods and Attributes",
      "",
      "## Why this matters",
      "",
      "Methods are functions that belong to a class, and understanding the different types of methods (instance, class, static) lets you organize your code more effectively. This lesson covers how to work with attributes and different method types in Python.",
      "",
      "## Instance methods",
      "",
      "Instance methods operate on individual objects and have access to instance attributes through `self`:",
      "",
      "~~~python",
      "class BankAccount:",
      "    def __init__(self, owner, balance=0):",
      "        self.owner = owner",
      "        self.balance = balance",
      "    ",
      "    def deposit(self, amount):",
      "        self.balance += amount",
      "        return self.balance",
      "    ",
      "    def withdraw(self, amount):",
      "        if amount > self.balance:",
      "            return 'Insufficient funds'",
      "        self.balance -= amount",
      "        return self.balance",
      "~~~",
      "",
      "## Class methods",
      "",
      "Class methods work with the class itself, not instances. Use the `@classmethod` decorator:",
      "",
      "~~~python",
      "class Date:",
      "    def __init__(self, year, month, day):",
      "        self.year = year",
      "        self.month = month",
      "        self.day = day",
      "    ",
      "    @classmethod",
      "    def from_string(cls, date_string):",
      "        year, month, day = date_string.split('-')",
      "        return cls(int(year), int(month), int(day))",
      "",
      "# Use class method as alternative constructor",
      "date = Date.from_string('2024-03-15')",
      "~~~",
      "",
      "The `cls` parameter refers to the class itself, similar to `self` for instances.",
      "",
      "## Static methods",
      "",
      "Static methods don't access instance or class data. Use `@staticmethod` decorator:",
      "",
      "~~~python",
      "class MathUtils:",
      "    @staticmethod",
      "    def add(x, y):",
      "        return x + y",
      "    ",
      "    @staticmethod",
      "    def is_even(number):",
      "        return number % 2 == 0",
      "",
      "# Call without creating instance",
      "result = MathUtils.add(5, 3)",
      "~~~",
      "",
      "Static methods are utility functions that logically belong to the class but don't need access to class or instance data.",
      "",
      "## Properties and computed attributes",
      "",
      "Use the `@property` decorator to create computed attributes:",
      "",
      "~~~python",
      "class Circle:",
      "    def __init__(self, radius):",
      "        self.radius = radius",
      "    ",
      "    @property",
      "    def area(self):",
      "        return 3.14159 * self.radius ** 2",
      "    ",
      "    @property",
      "    def diameter(self):",
      "        return self.radius * 2",
      "",
      "circle = Circle(5)",
      "print(circle.area)      # Access like attribute, not method",
      "print(circle.diameter)  # No parentheses needed",
      "~~~",
      "",
      "## Private attributes",
      "",
      "Python uses underscore convention for private attributes (not enforced, but signals intent):",
      "",
      "~~~python",
      "class User:",
      "    def __init__(self, username, password):",
      "        self.username = username",
      "        self._password = password  # Private by convention",
      "    ",
      "    def check_password(self, password):",
      "        return self._password == password",
      "~~~",
      "",
      'Single underscore `_` means "private by convention." Double underscore `__` triggers name mangling (advanced, rarely needed).',
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Instance method | def method(self): | method() { |",
      "| Class method | @classmethod | static method() { |",
      "| Static method | @staticmethod | static method() { |",
      "| Getter | @property | get prop() { |",
      "| Private | _attribute | #attribute (ES2022) |",
      "",
      "## Quick practice",
      "",
      "1. Create a Temperature class with Celsius and Fahrenheit conversion methods",
      "2. Add a class method to create Temperature from Fahrenheit",
      "3. Use @property for automatic temperature conversions",
      "4. Add a static method to validate temperature values",
      "5. Use private attributes for internal calculations",
      "",
      "## Takeaway",
      "",
      "Understanding method types and attribute access patterns lets you design cleaner, more maintainable classes. Instance methods for object behavior, class methods for alternative constructors, static methods for utilities, and properties for computed values.",
    ].join("\n"),
  },
  "Object-Oriented Programming::Inheritance and Polymorphism": {
    estimatedTime: 120,
    content: [
      "# Inheritance and Polymorphism",
      "",
      "## Why this matters",
      "",
      "Inheritance lets you create new classes based on existing ones, reusing and extending functionality. Polymorphism allows different classes to be used interchangeably. Together, they enable flexible, maintainable code designs.",
      "",
      "## Basic inheritance",
      "",
      "~~~python",
      "class Animal:",
      "    def __init__(self, name):",
      "        self.name = name",
      "    ",
      "    def speak(self):",
      "        return 'Some sound'",
      "",
      "class Dog(Animal):  # Dog inherits from Animal",
      "    def speak(self):  # Override parent method",
      "        return f'{self.name} says woof!'",
      "",
      "class Cat(Animal):",
      "    def speak(self):",
      "        return f'{self.name} says meow!'",
      "",
      "dog = Dog('Buddy')",
      "cat = Cat('Whiskers')",
      "print(dog.speak())  # Buddy says woof!",
      "print(cat.speak())  # Whiskers says meow!",
      "~~~",
      "",
      "Child classes inherit attributes and methods from parent classes, and can override them.",
      "",
      "## Using super()",
      "",
      "The `super()` function calls methods from the parent class:",
      "",
      "~~~python",
      "class Vehicle:",
      "    def __init__(self, brand, model):",
      "        self.brand = brand",
      "        self.model = model",
      "    ",
      "    def info(self):",
      "        return f'{self.brand} {self.model}'",
      "",
      "class ElectricCar(Vehicle):",
      "    def __init__(self, brand, model, battery_size):",
      "        super().__init__(brand, model)  # Call parent constructor",
      "        self.battery_size = battery_size",
      "    ",
      "    def info(self):",
      "        base_info = super().info()  # Call parent method",
      "        return f'{base_info} (Battery: {self.battery_size} kWh)'",
      "",
      "tesla = ElectricCar('Tesla', 'Model 3', 75)",
      "print(tesla.info())  # Tesla Model 3 (Battery: 75 kWh)",
      "~~~",
      "",
      "## Polymorphism",
      "",
      "Different classes with the same method interface can be used interchangeably:",
      "",
      "~~~python",
      "def make_animal_speak(animal):",
      "    print(animal.speak())",
      "",
      "animals = [Dog('Rex'), Cat('Fluffy'), Dog('Max')]",
      "for animal in animals:",
      "    make_animal_speak(animal)  # Works with any Animal subclass",
      "~~~",
      "",
      'Polymorphism means "many forms" - the same interface works with different types.',
      "",
      "## Method resolution order (MRO)",
      "",
      "Python looks for methods in a specific order:",
      "",
      "~~~python",
      "class A:",
      "    def method(self):",
      "        return 'A'",
      "",
      "class B(A):",
      "    def method(self):",
      "        return 'B'",
      "",
      "class C(B):",
      "    pass",
      "",
      "obj = C()",
      "print(obj.method())  # 'B' - searches C, then B, then A",
      "print(C.__mro__)     # Show method resolution order",
      "~~~",
      "",
      "## Multiple inheritance (advanced)",
      "",
      "Python supports inheriting from multiple classes:",
      "",
      "~~~python",
      "class Flyer:",
      "    def fly(self):",
      "        return 'Flying!'",
      "",
      "class Swimmer:",
      "    def swim(self):",
      "        return 'Swimming!'",
      "",
      "class Duck(Flyer, Swimmer):  # Inherits from both",
      "    def quack(self):",
      "        return 'Quack!'",
      "",
      "duck = Duck()",
      "print(duck.fly())    # Flying!",
      "print(duck.swim())   # Swimming!",
      "print(duck.quack())  # Quack!",
      "~~~",
      "",
      "Use multiple inheritance carefully - composition is often clearer.",
      "",
      "## Abstract base classes",
      "",
      "Define interfaces that subclasses must implement:",
      "",
      "~~~python",
      "from abc import ABC, abstractmethod",
      "",
      "class Shape(ABC):",
      "    @abstractmethod",
      "    def area(self):",
      "        pass",
      "    ",
      "    @abstractmethod",
      "    def perimeter(self):",
      "        pass",
      "",
      "class Rectangle(Shape):",
      "    def __init__(self, width, height):",
      "        self.width = width",
      "        self.height = height",
      "    ",
      "    def area(self):",
      "        return self.width * self.height",
      "    ",
      "    def perimeter(self):",
      "        return 2 * (self.width + self.height)",
      "~~~",
      "",
      "You cannot instantiate Shape directly - subclasses must implement abstract methods.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Inherit | class Child(Parent): | class Child extends Parent { |",
      "| Call parent | super().method() | super.method() |",
      "| Multiple inheritance | class C(A, B): | Not built-in (use mixins) |",
      "| Abstract class | ABC + @abstractmethod | Not built-in (TypeScript has interfaces) |",
      "",
      "## Quick practice",
      "",
      "1. Create an Employee base class with name and salary",
      "2. Create Manager and Developer subclasses with specific methods",
      "3. Use super() to extend the base __init__ method",
      "4. Create a function that works with any Employee (polymorphism)",
      "5. Try creating an abstract base class for shapes",
      "",
      "## Takeaway",
      "",
      "Inheritance creates class hierarchies that mirror real-world relationships. Use super() to extend parent functionality, override methods for specialized behavior, and leverage polymorphism for flexible code. Abstract base classes define contracts that subclasses must fulfill.",
    ].join("\n"),
  },
  "Functions & Modules::Lambda and Higher-Order Functions": {
    estimatedTime: 20,
    content: [
      "# Lambda and Higher-Order Functions",
      "",
      "## Why this matters",
      "",
      "Higher-order functions are functions that work with other functions. Python supports this style very naturally, and lambdas give you a compact way to express small one-off functions.",
      "",
      "## Lambda expressions",
      "",
      "~~~python",
      "double = lambda x: x * 2",
      "print(double(5))",
      "~~~",
      "",
      "Use lambda for very small expressions. If the logic becomes complex, switch back to def for readability.",
      "",
      "## map, filter, and sorted",
      "",
      "~~~python",
      "numbers = [1, 2, 3, 4]",
      "doubled = list(map(lambda x: x * 2, numbers))",
      "evens = list(filter(lambda x: x % 2 == 0, numbers))",
      "ordered = sorted(numbers, key=lambda x: -x)",
      "~~~",
      "",
      "## Higher-order functions",
      "",
      "A higher-order function can accept another function as input or return one as output.",
      "",
      "## Python versus JavaScript",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Anonymous function | lambda | arrow function |",
      "| Map | map | map |",
      "| Filter | filter | filter |",
      "| Sort callback | key= | sort comparator |",
      "",
      "## Quick practice",
      "",
      "1. Use lambda to square numbers.",
      "2. Filter a list of even values.",
      "3. Sort a list of names by length.",
      "4. Rewrite a lambda as a regular def when it gets long.",
      "",
      "## Takeaway",
      "",
      "Lambda and higher-order functions are great tools, especially for data transformation. Use them when they make the code shorter and clearer, not just because they look clever.",
    ].join("\n"),
  },
  "Functions & Modules::Modules and Imports": {
    estimatedTime: 20,
    content: [
      "# Modules and Imports",
      "",
      "## Why this matters",
      "",
      "Modules are how Python code stays organized as projects grow. They let you split logic into files, reuse code, and keep related concepts together.",
      "",
      "## Importing code",
      "",
      "~~~python",
      "import math",
      "from datetime import datetime",
      "~~~",
      "",
      "You can import whole modules or specific names from a module.",
      "",
      "## Creating your own module",
      "",
      "If you place functions in a file like helpers.py, you can import them elsewhere.",
      "",
      "## __name__ guard",
      "",
      "~~~python",
      "def main():",
      "    print('Run the script directly')",
      "",
      "if __name__ == '__main__':",
      "    main()",
      "~~~",
      "",
      "This keeps code from running automatically when a file is imported.",
      "",
      "## Python versus JavaScript modules",
      "",
      "| Concept | Python | JavaScript |",
      "| --- | --- | --- |",
      "| Import whole file | import module | import * as module |",
      "| Import one item | from module import name | named import |",
      "| Entry-point guard | __name__ == '__main__' | separate entry file |",
      "",
      "## Quick practice",
      "",
      "1. Create a helper function in a separate file.",
      "2. Import math and use sqrt.",
      "3. Add a __name__ guard to a script.",
      "4. Split a tiny script into two files.",
      "",
      "## Takeaway",
      "",
      "Modules are the point where small scripts start becoming maintainable programs. This is a habit worth building early, especially if you are used to modular JavaScript code.",
    ].join("\n"),
  },
};

export function getLessonContent({
  moduleTitle,
  title,
  description,
  content,
}: LessonContentInput): string {
  const key = `${moduleTitle}::${title}`;
  const override = lessonOverrides[key]?.content;
  if (!override) return content;

  const wordCount = content.trim().split(/\s+/).filter(Boolean).length;
  if (wordCount >= 40) return content;

  return override || `${description}\n\n${content}`;
}

export function getLessonEstimatedTime(
  moduleTitle: string,
  title: string,
  fallback: number
): number {
  const key = `${moduleTitle}::${title}`;
  return lessonOverrides[key]?.estimatedTime ?? fallback;
}
