// Achievement seed data

export const achievements = [
  // First Steps
  {
    name: "First Steps",
    description: "Complete your first lesson",
    icon: "👣",
    category: "Learning",
    criteria: "Complete any lesson",
    xpReward: 10,
    tier: "Bronze",
  },
  {
    name: "Hello, Python!",
    description: "Complete Module 1: Python Setup & Fundamentals",
    icon: "🐍",
    category: "Modules",
    criteria: "Complete Module 1",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Data Master",
    description: "Complete Module 2: Data Structures & Control Flow",
    icon: "📊",
    category: "Modules",
    criteria: "Complete Module 2",
    xpReward: 75,
    tier: "Silver",
  },
  {
    name: "Function Expert",
    description: "Complete Module 3: Functions & Modules",
    icon: "⚙️",
    category: "Modules",
    criteria: "Complete Module 3",
    xpReward: 75,
    tier: "Silver",
  },

  // Project Achievements
  {
    name: "Calculator Pro",
    description: "Build your first Python project",
    icon: "🔢",
    category: "Projects",
    criteria: "Complete CLI Calculator project",
    xpReward: 100,
    tier: "Bronze",
  },
  {
    name: "Task Master",
    description: "Build a fully functional todo app",
    icon: "✅",
    category: "Projects",
    criteria: "Complete Todo List Manager project",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Text Wizard",
    description: "Create a modular text processing tool",
    icon: "📝",
    category: "Projects",
    criteria: "Complete Text Processing CLI Tool project",
    xpReward: 150,
    tier: "Silver",
  },

  // Exercise Achievements
  {
    name: "Problem Solver",
    description: "Complete 10 exercises",
    icon: "💡",
    category: "Exercises",
    criteria: "Complete 10 exercises",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Coding Machine",
    description: "Complete 25 exercises",
    icon: "⚡",
    category: "Exercises",
    criteria: "Complete 25 exercises",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "Exercise Champion",
    description: "Complete 50 exercises",
    icon: "🏆",
    category: "Exercises",
    criteria: "Complete 50 exercises",
    xpReward: 200,
    tier: "Gold",
  },

  // Streak Achievements
  {
    name: "Consistent Learner",
    description: "Maintain a 7-day learning streak",
    icon: "🔥",
    category: "Streaks",
    criteria: "7-day streak",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Dedication Master",
    description: "Maintain a 30-day learning streak",
    icon: "🔥🔥",
    category: "Streaks",
    criteria: "30-day streak",
    xpReward: 200,
    tier: "Silver",
  },
  {
    name: "Unstoppable",
    description: "Maintain a 100-day learning streak",
    icon: "🔥🔥🔥",
    category: "Streaks",
    criteria: "100-day streak",
    xpReward: 500,
    tier: "Gold",
  },

  // Milestone Achievements
  {
    name: "Quarter Way",
    description: "Reach 25% overall completion",
    icon: "📈",
    category: "Milestones",
    criteria: "25% completion",
    xpReward: 100,
    tier: "Bronze",
  },
  {
    name: "Halfway There",
    description: "Reach 50% overall completion",
    icon: "🎯",
    category: "Milestones",
    criteria: "50% completion",
    xpReward: 200,
    tier: "Silver",
  },
  {
    name: "Almost Done",
    description: "Reach 75% overall completion",
    icon: "🚀",
    category: "Milestones",
    criteria: "75% completion",
    xpReward: 300,
    tier: "Gold",
  },
  {
    name: "Python Master",
    description: "Complete 100% of the learning program",
    icon: "👑",
    category: "Milestones",
    criteria: "100% completion",
    xpReward: 1000,
    tier: "Platinum",
  },

  // Speed Achievements
  {
    name: "Quick Learner",
    description: "Complete a module in under the estimated time",
    icon: "⚡",
    category: "Speed",
    criteria: "Complete any module faster than estimated",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Speed Runner",
    description: "Complete 3 modules faster than estimated",
    icon: "🏃",
    category: "Speed",
    criteria: "Complete 3 modules faster than estimated",
    xpReward: 150,
    tier: "Silver",
  },

  // Special Achievements
  {
    name: "Early Bird",
    description: "Complete a lesson before 8 AM",
    icon: "🌅",
    category: "Special",
    criteria: "Complete lesson before 8 AM",
    xpReward: 25,
    tier: "Bronze",
  },
  {
    name: "Night Owl",
    description: "Complete a lesson after 10 PM",
    icon: "🦉",
    category: "Special",
    criteria: "Complete lesson after 10 PM",
    xpReward: 25,
    tier: "Bronze",
  },
  {
    name: "Weekend Warrior",
    description: "Complete 5 lessons on weekends",
    icon: "⚔️",
    category: "Special",
    criteria: "Complete 5 lessons on Saturday or Sunday",
    xpReward: 75,
    tier: "Bronze",
  },
];
