// Achievement seed data

export const achievements = [
  // First Steps
  {
    name: "First Steps",
    description: "Complete your first lesson",
    icon: "GraduationCap",
    category: "Learning",
    criteria: "Complete any lesson",
    xpReward: 10,
    tier: "Bronze",
  },
  {
    name: "Hello, Python!",
    description: "Complete Module 1: Python Setup & Fundamentals",
    icon: "Snake",
    category: "Modules",
    criteria: "Complete Module 1",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Data Master",
    description: "Complete Module 2: Data Structures & Control Flow",
    icon: "BarChart3",
    category: "Modules",
    criteria: "Complete Module 2",
    xpReward: 75,
    tier: "Silver",
  },
  {
    name: "Function Expert",
    description: "Complete Module 3: Functions & Modules",
    icon: "Settings",
    category: "Modules",
    criteria: "Complete Module 3",
    xpReward: 75,
    tier: "Silver",
  },
  {
    name: "OOP Architect",
    description: "Complete Module 4: Object-Oriented Programming",
    icon: "Building2",
    category: "Modules",
    criteria: "Complete Module 4",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "File Ninja",
    description: "Complete Module 5: File I/O & Exception Handling",
    icon: "Folder",
    category: "Modules",
    criteria: "Complete Module 5",
    xpReward: 75,
    tier: "Silver",
  },
  {
    name: "Quality Guardian",
    description: "Complete Module 6: Testing with pytest",
    icon: "TestTube2",
    category: "Modules",
    criteria: "Complete Module 6",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "Package Wizard",
    description: "Complete Module 7: Package Management & Virtual Environments",
    icon: "Package",
    category: "Modules",
    criteria: "Complete Module 7",
    xpReward: 75,
    tier: "Silver",
  },
  {
    name: "Async Virtuoso",
    description: "Complete Module 8: Async Programming with asyncio",
    icon: "Zap",
    category: "Modules",
    criteria: "Complete Module 8",
    xpReward: 125,
    tier: "Gold",
  },
  {
    name: "Advanced Scholar",
    description: "Complete Module 9: Advanced Python Features",
    icon: "Brain",
    category: "Modules",
    criteria: "Complete Module 9",
    xpReward: 125,
    tier: "Gold",
  },
  {
    name: "Type Safety Pro",
    description: "Complete Module 10: Type Hints & Static Analysis",
    icon: "Search",
    category: "Modules",
    criteria: "Complete Module 10",
    xpReward: 100,
    tier: "Gold",
  },
  {
    name: "Web Alchemist",
    description: "Complete Module 11: Web Development",
    icon: "Globe",
    category: "Modules",
    criteria: "Complete Module 11",
    xpReward: 150,
    tier: "Gold",
  },
  {
    name: "Database Maestro",
    description: "Complete Module 12: Database Integration",
    icon: "Database",
    category: "Modules",
    criteria: "Complete Module 12",
    xpReward: 125,
    tier: "Gold",
  },
  {
    name: "Data Scientist",
    description: "Complete Module 13: Data Processing",
    icon: "TrendingUp",
    category: "Modules",
    criteria: "Complete Module 13",
    xpReward: 125,
    tier: "Gold",
  },
  {
    name: "DevOps Warrior",
    description: "Complete Module 14: DevOps & Automation",
    icon: "Rocket",
    category: "Modules",
    criteria: "Complete Module 14",
    xpReward: 125,
    tier: "Gold",
  },
  {
    name: "Blockchain Pioneer",
    description: "Complete Module 15: Web3 & Blockchain Integration",
    icon: "Link",
    category: "Modules",
    criteria: "Complete Module 15",
    xpReward: 100,
    tier: "Gold",
  },
  {
    name: "Performance Tuner",
    description: "Complete Module 16: Performance & Optimization",
    icon: "Gauge",
    category: "Modules",
    criteria: "Complete Module 16",
    xpReward: 125,
    tier: "Gold",
  },

  // Project Achievements
  {
    name: "Calculator Pro",
    description: "Build your first Python project",
    icon: "Calculator",
    category: "Projects",
    criteria: "Complete CLI Calculator project",
    xpReward: 100,
    tier: "Bronze",
  },
  {
    name: "Task Master",
    description: "Build a fully functional todo app",
    icon: "CheckCircle2",
    category: "Projects",
    criteria: "Complete Todo List Manager project",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Text Wizard",
    description: "Create a modular text processing tool",
    icon: "FileText",
    category: "Projects",
    criteria: "Complete Text Processing CLI Tool project",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Library Guardian",
    description: "Build a library management system",
    icon: "BookOpen",
    category: "Projects",
    criteria: "Complete Library Management System project",
    xpReward: 175,
    tier: "Silver",
  },
  {
    name: "Log Detective",
    description: "Create a log file analyzer",
    icon: "ClipboardList",
    category: "Projects",
    criteria: "Complete Log File Analyzer project",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Banking Expert",
    description: "Develop a banking system with tests",
    icon: "Building",
    category: "Projects",
    criteria: "Complete Banking System with Tests project",
    xpReward: 175,
    tier: "Gold",
  },
  {
    name: "Package Publisher",
    description: "Create and publish a Python package",
    icon: "Box",
    category: "Projects",
    criteria: "Complete Python Package Creator project",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Web Scraper Master",
    description: "Build an async web scraper",
    icon: "Share2",
    category: "Projects",
    criteria: "Complete Async Web Scraper project",
    xpReward: 175,
    tier: "Gold",
  },
  {
    name: "Toolkit Creator",
    description: "Create a decorator & metaclass toolkit",
    icon: "Wrench",
    category: "Projects",
    criteria: "Complete Decorator & Metaclass Toolkit project",
    xpReward: 175,
    tier: "Gold",
  },
  {
    name: "Type Master",
    description: "Build a type-safe calculator library",
    icon: "Hash",
    category: "Projects",
    criteria: "Complete Type-Safe Calculator Library project",
    xpReward: 150,
    tier: "Gold",
  },
  {
    name: "API Architect",
    description: "Build a REST API with FastAPI",
    icon: "Code",
    category: "Projects",
    criteria: "Complete REST API with FastAPI project",
    xpReward: 200,
    tier: "Gold",
  },
  {
    name: "Database Designer",
    description: "Design a multi-tenant database system",
    icon: "🗄️👥",
    category: "Projects",
    criteria: "Complete Multi-Tenant Database System project",
    xpReward: 175,
    tier: "Gold",
  },
  {
    name: "Data Wizard",
    description: "Create a data analysis dashboard",
    icon: "PieChart",
    category: "Projects",
    criteria: "Complete Data Analysis Dashboard project",
    xpReward: 175,
    tier: "Gold",
  },
  {
    name: "Pipeline Engineer",
    description: "Build a CI/CD pipeline",
    icon: "Workflow",
    category: "Projects",
    criteria: "Complete CI/CD Pipeline Builder project",
    xpReward: 150,
    tier: "Gold",
  },
  {
    name: "Blockchain Builder",
    description: "Create a Web3 dApp",
    icon: "Blocks",
    category: "Projects",
    criteria: "Complete Smart Contract Interaction dApp project",
    xpReward: 150,
    tier: "Gold",
  },
  {
    name: "Optimization Master",
    description: "Create a performance optimization suite",
    icon: "Zap",
    category: "Projects",
    criteria: "Complete Performance Optimization Suite project",
    xpReward: 175,
    tier: "Gold",
  },

  // Exercise Achievements
  {
    name: "Problem Solver",
    description: "Complete 10 exercises",
    icon: "Lightbulb",
    category: "Exercises",
    criteria: "Complete 10 exercises",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Coding Machine",
    description: "Complete 25 exercises",
    icon: "Code2",
    category: "Exercises",
    criteria: "Complete 25 exercises",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "Exercise Champion",
    description: "Complete 50 exercises",
    icon: "🏆👑",
    category: "Exercises",
    criteria: "Complete 50 exercises",
    xpReward: 200,
    tier: "Gold",
  },
  {
    name: "Unstoppable Solver",
    description: "Complete 100 exercises",
    icon: "Medal",
    category: "Exercises",
    criteria: "Complete 100 exercises",
    xpReward: 400,
    tier: "Platinum",
  },

  // Streak Achievements
  {
    name: "Consistent Learner",
    description: "Maintain a 7-day learning streak",
    icon: "🔥📅",
    category: "Streaks",
    criteria: "7-day streak",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Week Warrior",
    description: "Maintain a 14-day learning streak",
    icon: "Flame",
    category: "Streaks",
    criteria: "14-day streak",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "Dedication Master",
    description: "Maintain a 30-day learning streak",
    icon: "Flame",
    category: "Streaks",
    criteria: "30-day streak",
    xpReward: 200,
    tier: "Silver",
  },
  {
    name: "Unstoppable",
    description: "Maintain a 100-day learning streak",
    icon: "Flame",
    category: "Streaks",
    criteria: "100-day streak",
    xpReward: 500,
    tier: "Gold",
  },
  {
    name: "Eternal Flame",
    description: "Maintain a 365-day learning streak",
    icon: "Flame",
    category: "Streaks",
    criteria: "365-day streak",
    xpReward: 2000,
    tier: "Platinum",
  },

  // Milestone Achievements
  {
    name: "Getting Started",
    description: "Reach 10% overall completion",
    icon: "Sprout",
    category: "Milestones",
    criteria: "10% completion",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Quarter Way",
    description: "Reach 25% overall completion",
    icon: "Target",
    category: "Milestones",
    criteria: "25% completion",
    xpReward: 100,
    tier: "Bronze",
  },
  {
    name: "Halfway There",
    description: "Reach 50% overall completion",
    icon: "Target",
    category: "Milestones",
    criteria: "50% completion",
    xpReward: 200,
    tier: "Silver",
  },
  {
    name: "Almost Done",
    description: "Reach 75% overall completion",
    icon: "Rocket",
    category: "Milestones",
    criteria: "75% completion",
    xpReward: 300,
    tier: "Gold",
  },
  {
    name: "Python Master",
    description: "Complete 100% of the learning program",
    icon: "👑💎🌟",
    category: "Milestones",
    criteria: "100% completion",
    xpReward: 1000,
    tier: "Platinum",
  },

  // Speed Achievements
  {
    name: "Quick Learner",
    description: "Complete a module in under the estimated time",
    icon: "Zap",
    category: "Speed",
    criteria: "Complete any module faster than estimated",
    xpReward: 50,
    tier: "Bronze",
  },
  {
    name: "Speed Runner",
    description: "Complete 3 modules faster than estimated",
    icon: "Zap",
    category: "Speed",
    criteria: "Complete 3 modules faster than estimated",
    xpReward: 150,
    tier: "Silver",
  },
  {
    name: "Lightning Learner",
    description: "Complete 10 modules faster than estimated",
    icon: "Zap",
    category: "Speed",
    criteria: "Complete 10 modules faster than estimated",
    xpReward: 300,
    tier: "Gold",
  },

  // Special Achievements
  {
    name: "Early Bird",
    description: "Complete a lesson before 8 AM",
    icon: "Sun",
    category: "Special",
    criteria: "Complete lesson before 8 AM",
    xpReward: 25,
    tier: "Bronze",
  },
  {
    name: "Night Owl",
    description: "Complete a lesson after 10 PM",
    icon: "Moon",
    category: "Special",
    criteria: "Complete lesson after 10 PM",
    xpReward: 25,
    tier: "Bronze",
  },
  {
    name: "Weekend Warrior",
    description: "Complete 5 lessons on weekends",
    icon: "Zap",
    category: "Special",
    criteria: "Complete 5 lessons on Saturday or Sunday",
    xpReward: 75,
    tier: "Bronze",
  },
  {
    name: "Marathon Runner",
    description: "Complete 10 exercises in one session",
    icon: "Zap",
    category: "Special",
    criteria: "Complete 10 exercises in one session",
    xpReward: 100,
    tier: "Silver",
  },
  {
    name: "All-Nighter",
    description: "Study for 12+ hours straight",
    icon: "Coffee",
    category: "Special",
    criteria: "Accumulate 12+ hours in one day",
    xpReward: 50,
    tier: "Bronze",
  },
];
